# Generated by Django 5.2.1 on 2025-05-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='tg_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='tg_username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram username'),
        ),
    ]
